<div class="clearfix">
       <section style="margin-top:1px;" class="generalwrapper clearfix">
            <div class="container-content">

                    <div style="margin:15px 0;" id="content" class="col-lg-12 col-md-12 col-sm-8 col-xs-12 clearfix">
                      <h3 class="judul">Syarat dan Ketentuan</h3>
<p>Persyaratan dan ketentuan di bawah ini wajib di baca terlebih dahulu sebelum menggunakan situs ini. Pengguna yang mengakses situs www.Ipapa.co.id berarti menerima dan tunduk terhadap syarat dan ketentuan di bawah ini.</p>

<p>Pengguna situs www.ipapa.co.id, yang dikelola oleh PT. ZMG Telekomunikasi Servise Indonesia adalah berdasarkan penerimaan dan penundukan terhadap syarat-syarat ketentuan penggunaan dibawah ini, namun tidak terbatas pada Kerahasiaan, FAQs, dan judul-judul yang lainnya yang menjadi suatu bagian yang tidak terpisahkan dari Syarat dan Ketentuan dan termasuk di dalamnya referensi dan istilah yang digunakan. Ketentuan-ketentuan dibawah ini dapat kami ubah, modifikasi dan hapus sewaktu-waktu tanpa pemberitahuan terlebih dahulu.</p>
<p>Syarat wajib ini harus secara berkala dibaca oleh pengguna www.Ipapa.co.id, dan dengan melanjutkan penggunaan Situs ini setelah perubahan yang ada pada Syarat dan ketentuan, berarti pengunjung, pengguna, Pengguna Terdaftar (“Anda” atau “Pengguna”) menyatakan setuju dan sepakat terhadap perubahan yang ada di situs ini. Apabila Anda menggunakan jasa lain milik Kami, maka penggunaan Anda akan berdasarkan penundukan terhadap Syarat dan Ketentuan yang berlaku bagi jasa tersebut.</p>
1. Penggunaan Situs<br>
<p style="margin-left:15px;">Ipapa dan PT. ZMG Telekomunikasi Servise Indonesia mempunyai hak penuh dalam mengontrol website ipapa.co.id, Ipapa dapat sewaktu-waktu merubah, memodifikasi, mengganti, menukar, menahan, atau menghapus segala sesuatu yang terdapat didalam website untuk kepentingan keamanan dan pengoptimalan kinerja website, atau apabila dalam keaadaan mendesak atau memaksa atau dalam istilah hukum di sebut force majeure.
Seorang pengguna hanya dapat menggunakan atau mengakses situs ipapa.co.id untuk tujuan yang tidak melanggar hukum, apabila di temukan seorang pengguna yang mengakses ipapa.co.id melakukan tindakan yang melanggar hukum, Ipapa atau PT. ZMG Telekomunikasi Servise Indonesia tidak bertanggung jawab atas kerugian yang muncul akibat hal-hal yang di akibatkan oleh pengguna.
Pengguna yang berusia di bawah 18 tahun harus didampingi oleh orang tua dalam mengakses website ipapa.co.id, kerugian yang timbul akibat pengguna dibawah umur yang tidak didampingi oleh orang tua bukan tanggung jawab Ipapa dan PT. ZMG Telekomunikasi Servise Indonesia.</p>
2. Larangan Penggunaan<br>
<p style="margin-left:15px;">Anda dengan ini sepakat untuk tidak menggunakan Situs atau Konten ini untuk hal yang melawan hukum atau aktivitas tanpa izin, Anda sepakat bahwa Anda tidak akan menggunakan peralatan, perangkat lunak, atau teknologi lain yang dapat menghalangi atau berupaya untuk menghalangi cara kerja Situs Ipapa ini. Anda sepakat untuk tidak menggunakan Situs ini atau Konten yang terdapat didalam situs untuk tujuan komersial. Anda sepakat untuk tidak mengupayakan, membuat atau mengupayakan, mencari, mengutus agen otomatis atau teknologi bentuk lainnya untuk mengumpulkan, mendapatkan, atau hal lainnya untuk berinteraksi dengan Situs ini.
Sehubungan dengan persyaratan penggunaan Situs, Anda atau pengguna sepakat untuk tidak menggunakan Situs atau Konten untuk tujuan komersial atau baik secara langsung atau tidak untuk selain keperluan pribadi atau untuk tujuan yang melawan hukum, komersial, dilarang oleh hukum atau perbuatan yang melanggar Syarat, kecuali dengan persetujuan tertulis dari Ipapa.co.id atau PT. ZMG Telekomunikasi Servise Indonesia, Anda atau pengguna sepakat untuk tidak mengubah, menyalin, membagikan, mengirimkan, menampilkan, melaksanakan, mereproduksi, mengumumkan, mengizinkan, mencipatakan kreasi derivatif dari, mengalihkan, atau menjual atau menjual kembali tiap informasi didalam situs, perangkat lunak, produk atau jasa yang diperoleh sehubungan dengan Situs. Sebagai tambahan, Anda sepakat untuk tidak :</p>
<p style="margin-left:20px;">1. Menggunakan Situs ini atau Konten untuk tujuan komersial tanpa seizin Ipapa atau PT. ZMG Telekomunikasi Servise Indonesia
<br>2. Mengakses, mengawasi atau menyalin tiap Konten dalam Situs menggunakan teknologi, perangkat lunak, program apapun baik secara manual ataupun otomatis untuk tujuan lain tanpa izin tegas tertulis dari Ipapa atau PT. ZMG Telekomunikasi Service Indonesia
<br>3. Melakukan tindakan yang mengakibatkan atau dapat mengakibatkan, suatu beban yang tidak wajar pada infrastruktur kami, dalam hal ini situs Ipapa.co.id
<br>4. Membuat suatu tautan utama bagi Situs (termasuk namun tidak terbatas pada jalur pemesanan) untuk tujuan apapun tanpa persetujuan tertulis Ipapa atau PT. ZMG Telekomunikasi Servise Indonesia
<br>5. Menjual kembali isi situs, menggunakan, menyalin, melakukan pengawasan (contoh memasang spider, scrape), menampilkan, mengunduh atau melakukan produksi tiap Konten, perangkat lunak, produk, jasa yang tersedia dalam Situs untuk tujuan komersil atau tujuan atau kegiatan persaingan usaha
<br>6. Melakukan percontohan (“frame” atau “mirror”) atau mendirikan bagian dari Situs Ipapa ini pada Situs web lainnya tanpa persetujuan tertulis terlebih dahulu
<br>7. Mengirimkan suatu pengumuman kepada atau melalui Situs selain Ipapa yang melawan hukum berdasarkan hukum peraturan yang berlaku, ataupun pengumuman yang dapat mendukung kegiatan kriminal ataupun hal-hal yang dapat menimbulkan efek negative Ipapa dan PT. ZMG Telekomunikasi Servise Indonesia
<br>8. Mengirimkan atau menyediakan tautan kepada situs lain atau pengumuman yang mengandung suatu materi yang dapat dianggap membahayakan, cabul, berbau pornografi, tidak senonoh, berbau kekerasan, rasis, diskriminasi, penghinaan, pengancaman, pelecehan, penindasan, kebencian atau tidak pantas
<br>9. Mengirimkan atau menyediakan tautan kepada tiap pengumuman yang mengandung hal pencemaran nama baik, fitnah, dan kebohongan ke pihak-pihak lain
<br>10. Mengirimkan atau melakukan pengumuman yang dapat melanggar dan menyalahi hak kekayaan intelektual property atau hak lainnya dari badan atau orang tertentu termasuk namun tidak terbatas pada hak cipta, hak paten, hak merek, rahasia dagang, kerahasiaan, atau publikasi.
<br>11. Mengirimkan pengumuman yang mana dilarang oleh hukum yang berlaku atau melanggar hak dan kewajiban yang ada berdasarkan hubungan kontrak
<br>12. Meniru orang atau badan atau memalsukan keadaan atau memberikan gambaran yang salah terhadap suatu afiliasi akan seseorang atau badan atau mengambil identitas palsu apabila tujuannya adalah untuk menyesatkan, membohongi atau menipu
<br>13. Memanipulasi, memalsukan dengan tujuan menyamarkan asal dari pengumuman yang Anda berikan dan anda publikasikan kekhalayak ramai
<br>14. Menggunakan Situs Ipapa ini dengan cara yang dapat merusak, melumpuhkan, menghalangi, atau mengganggu penggunaan Situs atau pengguna peralatan computer lainnya, atau mengakibatkan kerusakan, gangguan atau membatasi fungsi dari perangkat lunak, perangkat keras atau peralatan telekomunikasi
<br>15. Mencoba untuk mendapatkan akses terhadap penggunaan yang tidak sah atas Situs Ipapa atau Situs website terkait lainnya, akun lain, system komputer, jaringan yang terhubung dengan Situs melalui hacking, pencurian kata sandi atau hal serupa lainnya, dan dapat mengakibatkan hal berbahaya dan mengancam lainnya
<br>16. Mendapatkan atau berupaya mendapatkan materi atau informasi melalui cara-cara yang bukan sengaja disediakan oleh Situs (termasuk namun tidak terbatas tujuan lain penyediaan oleh Situs), namun tidak terbatas dalam mendapatkan atau mengumpulkan informasi tentang pihak lainnya seperti alamat email ataupun melalui media elektronik lainnya
<br>17. Terlibat dalam tindakan penipuan atau tindakan yang ditujukan untuk memanipulasi suatu hasil pencarian pada mesin pencari (SERP) dalam istilah ini bisa disebut sebagai negative SEO atau mempekerjakan Pakar Search Engine Optimization (SEO) yang dianggap bertentangan dengan engine pencarian umumnya. Praktek SEO adalah dianggap suatu tindakan yang tidak etis atau “spamdexing” termasuk namun tidak terbatas pada penyelubungan, meta data pada script atau code HTMLdi situs ipapa, tag judul, scraping konten, skema link, negative SEO, pencarian kata kunci, text tersembunyi atau tautan tersembunyi, skema tautan, komentar mengandung spam dan hal lainnya
18. Melakukan tindakan lainnya yang dapat mengakibatkan kerusakan pada Situs, Ipapa atau afiliasinya dan termasuk karyawan didalamnya, reputasi Ipapa atau karyawan didalamnya atau hal lain yang dapat menimbulkan dampak negative pada perusahaan
</p>                  

                   </div>
                    
                </div>
            </div><!-- end container -->
        </section><!-- end generalwrapper -->
    </div> </div><br>
